spring.application.name=backEnd
server.port=8080
yandex.folder-id = b1gif30e3juemal01sav
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
groq.service.url=http://localhost:8000